### ISSUE TITLE
nose2 tests failed

### ISSUE THREAD

**Issue by fywu85** [berkeleyflow/flow#9]
`nose2 -s tests/fast_tests` failed with the following error log:

```
FAIL: test_apply_lane_change_direction (tests.fast_tests.test_environment_base_class.TestApplyingActionsWithSumo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/flow/tests/fast_tests/test_environment_base_class.py", line 266, in test_apply_lane_change_direction
    np.testing.assert_array_almost_equal(lane1, expected_lane1, 1)
  File "/opt/conda/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 963, in assert_array_almost_equal
    precision=decimal)
  File "/opt/conda/lib/python3.6/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 1 decimals

(mismatch 20.0%)
 x: array([0, 1, 0, 0, 0])
 y: array([0, 1, 0, 1, 0])
----------------------------------------------------------------------
Ran 88 tests in 370.781s

FAILED (failures=1, skipped=1)
```

Environment configuration:

- Flow build: a85691d
- Ray build: 6a737731 (version 0.4.0)
- SUMO build: 621ab1d3b8
- OS: Debian GNU/Linux 9 (stretch)

Please help resolve this. Thanks!

**Comment by eugenevinitsky** [comment]
Is this resolved @fywu85

**Comment by eugenevinitsky** [comment]
Also thank you for the ultra-thorough environment config!

**Comment by fywu85** [comment]
See suggested solutions in #30.
